apiVersion: v1
kind: PersistentVolume 
metadata:
  name: nfspv-ehsm
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: nfs
  nfs:
    path: /nfs_ehsm_db
    server: 10.112.241.81
